# Stage 1: Builder
FROM golang:1.25.5-alpine AS builder

WORKDIR /app

# Install git jika diperlukan untuk download dependency private/tertentu
# RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build Binary "go-inventory"
# ldflags -s -w untuk memperkecil ukuran binary
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o go-inventory cmd/api/main.go

# Stage 2: Runner
FROM alpine:latest

WORKDIR /root/

# Install CA Certificates (wajib untuk request HTTPS) dan Timezone data
RUN apk --no-cache add ca-certificates tzdata

COPY --from=builder /app/go-inventory .

EXPOSE 3001

CMD ["./go-inventory"]