FROM golang:1.23-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

# Build Binary "go-inventory"
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o go-inventory cmd/api/main.go

FROM alpine:latest
WORKDIR /root/
RUN apk --no-cache add ca-certificates
COPY --from=builder /app/go-inventory .

EXPOSE 3000
CMD ["./go-inventory"]